language: ruby
rvm: 2.1.4
deploy:
  provider: heroku
  api_key:
    secure: Wpy1HxmyWjbT74i5rye2zErubOTVnGECi9Ot6BccFtT+k0LZA28PFW8hUkQouFoV5vaEyhOHA4S13JbNgSwf1mE6eT2OL5C7i3lDF1sOB9ndVeaZjnGTKZbiicIgPdujlTObodQqGy+hLJobm/Y9mP1o0v/pA/6O7olcKI8q7/Y=
  app: scotlug-staging
  strategy: api
before_script:
  - psql -c 'create database scotlug_test;' -U postgres
notifications:
  irc: "chat.freenode.net#scotlug"
